name: collision-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - matplotlib
  - pip
  - pip:
      - ultralytics
      - cython
      - lap
      - filterpy
      - scikit-learn
      - yolox-tracker
