name: CollisionVision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - matplotlib
  - click
  - flask
  - jinja2
  - networkx
  - pandas
  - pillow
  - protobuf
  - pyparsing
  - pytz
  - pyyaml
  - requests
  - scikit-learn
  - seaborn
  - six
  - sympy
  - tornado
  - werkzeug
  - wheel
  - psycopg2           # PostgreSQL adapter for Python
  - sqlalchemy         # ORM for database operations
  - pip
  - pip:
      - ultralytics>=8.0.0
      - cython
      - lap
      - filterpy
      - torch>=1.7.0
      - torchvision>=0.8.1
      - onemetric
      - loguru
      - scipy
      - tqdm
      - tensorboard
      - thop  # FLOPs calculation
      # - yolox  # For ByteTrack integration