name: CollisionVision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - opencv
  - matplotlib
  - pip
  - pip:
      - ultralytics>=8.0.0
      - cython
      - lap
      - filterpy
      - scikit-learn
      - torch>=1.7.0
      - torchvision>=0.8.1
      - onemetric
      - loguru
      - scipy
      - tqdm
      - tensorboard
      - thop  # FLOPs calculation
      #- yolox  # For ByteTrack integration
